const STORAGE_KEY = "tku_timetable_v5";
const DAYS=[{key:1,name:"一"},{key:2,name:"二"},{key:3,name:"三"},{key:4,name:"四"},{key:5,name:"五"},{key:6,name:"六"},{key:7,name:"日"}];
const PERIODS=[[1,"08:10–09:00"],[2,"09:10–10:00"],[3,"10:10–11:00"],[4,"11:10–12:00"],[5,"12:10–13:00"],[6,"13:10–14:00"],[7,"14:10–15:00"],[8,"15:10–16:00"],[9,"16:10–17:00"],[10,"17:10–18:00"],[11,"18:10–19:00"],[12,"19:10–20:00"],[13,"20:10–21:00"],[14,"21:10–22:00"]].map(([number,time])=>({number,time}));
const DEFAULT_DISPLAY={days:{1:true,2:true,3:true,4:true,5:true,6:false,7:false},periods:{1:true,2:true,3:true,4:true,5:true,6:true,7:true,8:true,9:true,10:true,11:false,12:false,13:false,14:false},showSeat:true};
const DEMO={version:5,semester:"115-1 範例",student:{name:"範例學生",studentId:"DEMO0000"},display:clone(DEFAULT_DISPLAY),courses:[
{id:"2952",name:"高等微積分",customName:"",department:"TSNXB",grade:"2",className:"A",credits:"3",seatNumber:"033",pdf:"http://ap09.emis.tku.edu.tw/115_1/115_1_2952.PDF",description:"同一門課多個上課時段共用同一座號。",times:[{day:1,periods:[1,2],room:"S 420",teacher:"余"},{day:3,periods:[1],room:"S 420",teacher:"余"},{day:3,periods:[2],room:"S 420",teacher:"助教"}],note:"",journal:[]},
{id:"2951",name:"代數學（一）",customName:"",department:"TSNXB",grade:"2",className:"A",credits:"3",seatNumber:"040",pdf:"http://ap09.emis.tku.edu.tw/115_1/115_1_2951.PDF",description:"同一門課固定座號 040。",times:[{day:2,periods:[8,9],room:"S 420",teacher:"王"},{day:5,periods:[3],room:"S 420",teacher:"王"},{day:5,periods:[7],room:"S 420",teacher:"助教"}],note:"",journal:[]},
{id:"2954",name:"機率論",customName:"",department:"TSNXB",grade:"2",className:"A",credits:"3",seatNumber:"044",pdf:"http://ap09.emis.tku.edu.tw/115_1/115_1_2954.PDF",description:"機率論範例。",times:[{day:4,periods:[5,6],room:"C 013",teacher:"黃"},{day:5,periods:[4],room:"C 013",teacher:"黃"},{day:5,periods:[6],room:"C 002",teacher:"助教"}],note:"",journal:[]},
{id:"1458",name:"哲學專題",customName:"",department:"TGCHB",grade:"0",className:"B",credits:"2",seatNumber:"016",pdf:"",description:"哲學專題範例。",times:[{day:4,periods:[9,10],room:"E 414",teacher:"林"}],note:"",journal:[]}
]};
let state=loadData();let currentWeekOffset=0;let currentCourseId=null;
function clone(x){return JSON.parse(JSON.stringify(x));}
function normalise(data){const x=data&&typeof data==="object"?data:clone(DEMO);x.display={...clone(DEFAULT_DISPLAY),...(x.display||{}),days:{...DEFAULT_DISPLAY.days,...(x.display?.days||{})},periods:{...DEFAULT_DISPLAY.periods,...(x.display?.periods||{})}};x.student=x.student||{name:"",studentId:""};x.courses=Array.isArray(x.courses)?x.courses:[];return x;}
function loadData(){try{const raw=localStorage.getItem(STORAGE_KEY)||localStorage.getItem("tku_timetable_v4");return raw?normalise(JSON.parse(raw)):clone(DEMO);}catch{return clone(DEMO);}}
function saveData(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state));}
function esc(v){return String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");}
function uid(){return crypto?.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random()}`;}
function getMonday(offset=0){const d=new Date();const day=d.getDay();const diff=day===0?-6:1-day;d.setHours(0,0,0,0);d.setDate(d.getDate()+diff+offset*7);return d;}
function dateText(d){return `${d.getFullYear()}/${String(d.getMonth()+1).padStart(2,"0")}/${String(d.getDate()).padStart(2,"0")}`;}
function visibleDays(){return DAYS.filter(d=>state.display.days[d.key]);}
function visiblePeriods(){return PERIODS.filter(p=>state.display.periods[p.number]);}
function displayName(c){return c.customName?.trim()||c.name||"未命名課程";}
function getCourse(id){return state.courses.find(c=>String(c.id)===String(id));}
function renderHeader(){document.getElementById("semesterText").textContent=state.semester?`學期：${state.semester}`:"尚未同步";document.getElementById("studentName").textContent=state.student?.name||"尚未登入";document.getElementById("studentInfo").textContent=state.student?.studentId?`學號：${state.student.studentId}`:"目前使用本機課表";document.getElementById("settingStudentName").textContent=state.student?.name||"尚未取得";document.getElementById("settingStudentId").textContent=state.student?.studentId||"尚未取得";const mon=getMonday(currentWeekOffset);const sun=new Date(mon);sun.setDate(sun.getDate()+6);document.getElementById("weekText").textContent=`${dateText(mon)} ～ ${dateText(sun)}`;}
function coursesAt(day,period){const out=[];for(const course of state.courses){for(const t of course.times||[]){if(Number(t.day)===day&&(t.periods||[]).map(Number).includes(period))out.push({course,time:t});}}return out;}
function renderSchedule(){const root=document.getElementById("schedule");root.innerHTML="";const days=visibleDays();const periods=visiblePeriods();if(!days.length||!periods.length){root.innerHTML='<div class="no-courses">目前沒有顯示中的星期或節次。<br>請到右上角 ⚙ 開啟。</div>';return;}
const monday=getMonday(currentWeekOffset);root.style.setProperty("--day-count",String(days.length));
for(const day of days){const d=new Date(monday);d.setDate(monday.getDate()+day.key-1);const section=document.createElement("section");section.className="day-section";section.innerHTML=`<div class="day-title"><span>星期${day.name}</span><small>${dateText(d)}</small></div><div class="period-list"></div>`;const list=section.querySelector(".period-list");for(const p of periods){const row=document.createElement("div");row.className="period-row";row.innerHTML=`<div class="period-label"><strong>第${p.number}節</strong><span>${p.time}</span></div><div class="period-cell"></div>`;const cell=row.querySelector(".period-cell");const items=coursesAt(day.key,p.number);if(!items.length){cell.innerHTML='<div class="empty">—</div>';}else{for(const {course,time} of items){const btn=document.createElement("button");btn.type="button";btn.className="course-card";const seat=state.display.showSeat&&course.seatNumber?`<div class="course-seat">座號 ${esc(course.seatNumber)}</div>`:"";btn.innerHTML=`<div class="course-name">${esc(displayName(course))}</div><div class="course-meta">${esc(time.teacher||"")}${time.room?`　${esc(time.room)}`:""}</div>${seat}`;btn.addEventListener("click",()=>openCourse(course.id));cell.appendChild(btn);}}list.appendChild(row);}root.appendChild(section);}}
function renderSettings(){const dc=document.getElementById("dayChecks");dc.innerHTML="";for(const d of DAYS){const label=document.createElement("label");label.className="check-item";label.innerHTML=`<span>星期${d.name}</span><input type="checkbox" ${state.display.days[d.key]?"checked":""}>`;label.querySelector("input").addEventListener("change",e=>{state.display.days[d.key]=e.target.checked;saveData();renderSchedule();});dc.appendChild(label);}const pc=document.getElementById("periodChecks");pc.innerHTML="";for(const p of PERIODS){const label=document.createElement("label");label.className="check-item";label.innerHTML=`<span>第 ${p.number} 節<br><small>${p.time}</small></span><input type="checkbox" ${state.display.periods[p.number]?"checked":""}>`;label.querySelector("input").addEventListener("change",e=>{state.display.periods[p.number]=e.target.checked;saveData();renderSchedule();});pc.appendChild(label);}document.getElementById("showSeat").checked=!!state.display.showSeat;}
function render(){renderHeader();renderSchedule();renderSettings();updateNetwork();}
function showModal(id){document.getElementById("modalBackdrop").classList.remove("hidden");document.getElementById(id).classList.remove("hidden");document.getElementById("modalBackdrop").setAttribute("aria-hidden","false");document.body.classList.add("modal-open");}
function hideModals(){document.getElementById("modalBackdrop").classList.add("hidden");for(const id of ["courseModal","settingsModal"])document.getElementById(id).classList.add("hidden");document.getElementById("modalBackdrop").setAttribute("aria-hidden","true");document.body.classList.remove("modal-open");currentCourseId=null;}
function openCourse(id){const c=getCourse(id);if(!c)return;currentCourseId=String(id);document.getElementById("courseTitle").textContent=displayName(c);document.getElementById("courseSubtitle").textContent=`${c.department||""} · ${c.className||""}`;document.getElementById("customName").value=c.customName||"";document.getElementById("schoolName").textContent=c.name||"—";document.getElementById("courseIdText").textContent=c.id||"—";document.getElementById("seatNumber").textContent=c.seatNumber||"—";document.getElementById("credits").textContent=c.credits||"—";document.getElementById("department").textContent=c.department||"—";document.getElementById("gradeClass").textContent=`${c.grade||"—"} / ${c.className||"—"}`;document.getElementById("description").value=c.description||"";document.getElementById("note").value=c.note||"";const times=document.getElementById("timesList");times.innerHTML="";for(const t of c.times||[]){const day=DAYS.find(x=>x.key===Number(t.day));const el=document.createElement("div");el.className="time-item";el.innerHTML=`<div class="time-title">星期${esc(day?.name||t.day)} · 第 ${esc((t.periods||[]).join("、"))} 節</div><div class="time-sub">教室：${esc(t.room||"—")}</div><div class="time-teacher">授課：${esc(t.teacher||"—")}</div>`;times.appendChild(el);}document.getElementById("courseLinks").innerHTML=c.pdf?`<a href="${esc(c.pdf)}" target="_blank" rel="noopener">查看淡江課程 PDF ↗</a>`:"";renderJournal(c);showModal("courseModal");}
function renderJournal(c){const list=document.getElementById("journalList");list.innerHTML="";if(!c.journal?.length){list.innerHTML='<div class="hint">尚無記事。</div>';return;}for(const j of c.journal){const el=document.createElement("div");el.className="journal-item";el.innerHTML=`<div><strong>${esc(j.date)}</strong></div><div>${esc(j.text)}</div>`;list.appendChild(el);}}
function saveCourse(){const c=getCourse(currentCourseId);if(!c)return;c.customName=document.getElementById("customName").value.trim();c.note=document.getElementById("note").value;saveData();hideModals();render();}
function addJournal(){const c=getCourse(currentCourseId);if(!c)return;const text=prompt("輸入記事內容：");if(!text?.trim())return;c.journal=Array.isArray(c.journal)?c.journal:[];c.journal.unshift({id:uid(),date:new Date().toLocaleString("zh-TW",{hour12:false}),text:text.trim()});saveData();renderJournal(c);}
function clearCourses(){if(!confirm("確定要清除目前課表嗎？\n\n自訂課名、備註、記事與顯示設定會保留。"))return;state.courses=[];state.semester="";saveData();hideModals();render();alert("課表已清除。");}
function logoutApp(){if(!confirm("確定要登出並清除本機資料嗎？"))return;localStorage.removeItem(STORAGE_KEY);localStorage.removeItem("tku_timetable_v4");state={version:5,semester:"",student:{name:"",studentId:""},display:clone(DEFAULT_DISPLAY),courses:[]};saveData();hideModals();render();alert("已清除本機資料。");}
function exportJSON(){const blob=new Blob([JSON.stringify(state,null,2)],{type:"application/json"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download="tku-timetable.json";document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),500);}
async function importJSON(file){try{state=normalise(JSON.parse(await file.text()));saveData();render();alert("匯入成功。");}catch(e){alert(`匯入失敗：${e.message}`);}}
function loadDemo(){if(!confirm("載入範例課表並取代目前本機資料？"))return;state=clone(DEMO);saveData();hideModals();render();}
function openTKUSSO(){location.href="https://sso.tku.edu.tw/NEAI/loginrwd.jsp";}
function logoutTKUSSO(){location.href="https://sinfo.ais.tku.edu.tw/emisE/eTMW_OUT.aspx";}
function updateNetwork(){document.getElementById("networkStatus").textContent=navigator.onLine?"目前有網路":"離線可用";}
document.getElementById("prevWeek").addEventListener("click",()=>{currentWeekOffset--;renderHeader();renderSchedule();});
document.getElementById("nextWeek").addEventListener("click",()=>{currentWeekOffset++;renderHeader();renderSchedule();});
document.getElementById("todayButton").addEventListener("click",()=>{currentWeekOffset=0;renderHeader();renderSchedule();});
document.getElementById("settingsButton").addEventListener("click",()=>{renderSettings();showModal("settingsModal");});
document.getElementById("closeSettings").addEventListener("click",hideModals);
document.getElementById("closeCourse").addEventListener("click",hideModals);
document.getElementById("cancelCourse").addEventListener("click",hideModals);
document.getElementById("saveCourseButton").addEventListener("click",saveCourse);
document.getElementById("modalBackdrop").addEventListener("click",e=>{if(e.target.id==="modalBackdrop")hideModals();});
document.getElementById("addJournal").addEventListener("click",addJournal);
document.getElementById("showSeat").addEventListener("change",e=>{state.display.showSeat=e.target.checked;saveData();renderSchedule();});
document.getElementById("clearCoursesButton").addEventListener("click",clearCourses);
document.getElementById("logoutAppButton").addEventListener("click",logoutApp);
document.getElementById("exportData").addEventListener("click",exportJSON);
document.getElementById("importData").addEventListener("change",e=>{const f=e.target.files?.[0];if(f)importJSON(f);e.target.value="";});
document.getElementById("loadDemo").addEventListener("click",loadDemo);
document.getElementById("tkuLoginButton").addEventListener("click",openTKUSSO);
document.getElementById("tkuLogoutButton").addEventListener("click",logoutTKUSSO);
window.addEventListener("online",updateNetwork);window.addEventListener("offline",updateNetwork);
if("serviceWorker" in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("service-worker.js").catch(console.error));
render();
